/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    // 1. Start Here
    {
      type: 'category',
      label: '🚀 Start here',
      collapsed: false,
      items: [
        'index',
        'quickstart',
        'documentation-overview',
        'structure-map',
        'mermaid/index',
      ],
    },

    // 2. Architecture & Flows
    {
      type: 'category',
      label: 'Architecture & flows',
      collapsed: false,
      items: [
        'architecture-principles',
        {
          type: 'link',
          label: 'Diagrams overview',
          href: '/docs/diagrams/',
        },
        {
          type: 'category',
          label: 'Platform diagrams',
          items: [
            { type: 'autogenerated', dirName: 'mermaid/02-architecture' },
            { type: 'autogenerated', dirName: 'mermaid/03-platform-flows' },
            { type: 'autogenerated', dirName: 'mermaid/04-unified-master-flow' },
          ],
        },
      ],
    },

    // 3. Wallet & Data
    {
      type: 'category',
      label: 'Wallet & data',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'mermaid/07-wallet-architecture' },
        { type: 'autogenerated', dirName: 'mermaid/07-data-models' },
      ],
    },

    // 4. Governance & RFCs
    {
      type: 'category',
      label: 'Governance & RFCs',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'mermaid/06-governance' },
        'rfc/rfc-guidelines',
        { type: 'autogenerated', dirName: 'rfc' },
      ],
    },

    // 5. APIs, Automation & Tests
    {
      type: 'category',
      label: 'APIs & automation',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'api' },
        { type: 'autogenerated', dirName: 'automation' },
        { type: 'autogenerated', dirName: 'ci' },
        { type: 'autogenerated', dirName: 'tests' },
        { type: 'autogenerated', dirName: 'mermaid/08-api-contracts' },
        { type: 'autogenerated', dirName: 'mermaid/09-amy-agent' },
      ],
    },

    // 6. Meta & Reference
    {
      type: 'category',
      label: 'Meta & reference',
      collapsed: true,
      items: [
        'faq',
        'glossary',
        'contributors-guide',
        'maintenance-guide',
        'changelog',
        'manifest',
        'shortcuts',
      ],
    },
  ],
};

module.exports = sidebars;
