/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    // 1. Start Here
    {
      type: 'category',
      label: '🚀 Start here',
      collapsed: false,
      items: [
        'index',
        'quickstart',
        'documentation-overview',
        'structure-map',
        'mermaid/index',
      ],
    },

    // 2. Architecture & Flows
    {
      type: 'category',
      label: 'Architecture & flows',
      collapsed: false,
      items: [
        'architecture-principles',
        {
          type: 'link',
          label: 'Diagrams overview',
          href: '/docs/diagrams/',
        },
        {
          type: 'category',
          label: 'Platform diagrams',
          items: [
            { type: 'autogenerated', dirName: 'mermaid/02-architecture' },
            { type: 'autogenerated', dirName: 'mermaid/03-platform-flows' },
            { type: 'autogenerated', dirName: 'mermaid/04-unified-master-flow' },
          ],
        },
      ],
    },

    // 3. Wallet & Data
    {
      type: 'category',
      label: 'Wallet & data',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'mermaid/07-wallet-architecture' },
        { type: 'autogenerated', dirName: 'mermaid/07-data-models' },
      ],
    },

    // 4. Governance & RFCs
    {
      type: 'category',
      label: 'Governance & RFCs',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'mermaid/06-governance' },
        'rfc/rfc-guidelines',
        { type: 'autogenerated', dirName: 'rfc' },
      ],
    },

    // 5. APIs, Automation & Tests
    {
      type: 'category',
      label: 'APIs & automation',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'api' },
        { type: 'autogenerated', dirName: 'automation' },
        { type: 'autogenerated', dirName: 'ci' },
        { type: 'autogenerated', dirName: 'tests' },
        { type: 'autogenerated', dirName: 'mermaid/08-api-contracts' },
        { type: 'autogenerated', dirName: 'mermaid/09-amy-agent' },
      ],
    },

    // 6. Meta & Reference
    {
      type: 'category',
      label: 'Meta & reference',
      collapsed: true,
      items: [
        'faq',
        'glossary',
        'contributors-guide',
        'maintenance-guide',
        'changelog',
        'manifest',
        'shortcuts',
      ],
    },

    // 7. Public Documentation
    {
      type: 'category',
      label: '🌐 Public Documentation',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: '🚀 Start Here',
          items: [
            'public/overview/ogc-newfinity-overview',
            'public/whitepaper/ogc-whitepaper-public',
          ],
        },
        {
          type: 'category',
          label: '📘 OGCFinity Token',
          items: [
            'public/token/ogcfinity-token-summary',
            'public/token/tokenomics-visual',
            'public/token/ecosystem-economy',
          ],
        },
        {
          type: 'category',
          label: '🌱 Challenge Program',
          items: [
            'public/challenge/challenge-program-overview',
            'public/challenge/tracks-categories',
            'public/challenge/judging-and-rules',
            'public/challenge/challenge-faq',
          ],
        },
        {
          type: 'category',
          label: '🧠 Platform & Tools',
          items: [
            'public/platform/ai-agent-amy-overview',
            'public/platform/wallet-feature-sheet',
            'public/platform/platform-user-guide',
            'public/platform/subscriptions-overview',
          ],
        },
        {
          type: 'category',
          label: '🛠 Architecture',
          items: [
            'architecture-principles',
            {
              type: 'link',
              label: 'System Overview',
              href: '/docs/00-foundations/02-system-architecture-overview',
            },
          ],
        },
        {
          type: 'category',
          label: '📜 Governance',
          items: [
            {
              type: 'link',
              label: 'Governance Framework',
              href: '/docs/07-governance/118-governance-framework-overview',
            },
            {
              type: 'link',
              label: 'Token Governance',
              href: '/docs/07-governance/120-token-utility-and-governance-proposal-framework',
            },
          ],
        },
        {
          type: 'category',
          label: '📄 Legal & Compliance',
          items: [
            'public/legal/terms-of-use',
            'public/legal/privacy-policy',
            'public/legal/cookies-and-data-policy',
          ],
        },
        {
          type: 'category',
          label: '📊 Investors',
          items: [
            'public/investors/investor-information-pack',
            'public/investors/market-positioning',
            'public/investors/public-roadmap',
          ],
        },
        {
          type: 'category',
          label: '🎓 Glossary',
          items: [
            'glossary',
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;
